### PR TITLE
Move Findings data

### PR DESCRIPTION
**Pull request by thekaveman**
Moving the findings data to our [Wellbeing Data](https://github.com/CityofSantaMonica/WellbeingData) repository

This PR should only be merged after CityofSantaMonica/WellbeingData#2

### CODE REVIEW

**Comment by thekaveman** [comment]
@allejo another failing Travis/surge build...

This site is slightly different in that it is not a Jekyll site - just a simple HTML page with an angular app.

**Comment by allejo** [comment]
Was this rebased on top of #1's changes?

**Comment by thekaveman** [comment]
Uhh... no. So that makes sense, the travis config isn't even here yet. My bad.

**Comment by thekaveman** [comment]
@sevilturner I'm going to be updating this Findings data, so will be merging this pull request as it has moved to the [CityofSantaMonica/WellbeingData](https://github.com/CityofSantaMonica/WellbeingData) repo.

**Comment by thekaveman** [comment]
@allejo when you get a chance, can you look at that Travis build error? It's trying to `rake`, I'm not sure why, and that is failing. 

I made some minor changes to the build to account for this not being a Jekyll site, FYI.

**Comment by allejo** [comment]
So `rake` is executed by default for ruby projects on Travis since that's what I had originally configured it to be; setting `language: bash` in the **travis.yml** fixed that.

I never got around to setting up environment variables for this repo, so do you mind doing that?

## Surge.sh Auth

You're going to need to set up the following two environment variables in Travis: `SURGE_LOGIN` and `SURGE_TOKEN`. [Here's how you can get those credentials.](https://surge.sh/help/integrating-with-travis-ci)

## GitHub PR Status Updates

There is the `GITHUB_AUTH_USER` environment variable which is the username of [the github account whose token is being used](https://github.com/CityofSantaMonica/wellbeing-findings/blob/move-data/.travis.yml#L18). In Travis, the `GITHUB_PR_TOKEN` environment variable needs to be set to [the token you generated through GitHub](https://github.com/settings/tokens); this token should have the `repo:status` permission (that's the only permission that's needed).

---

The [Travis HackTheBeach settings](https://travis-ci.org/CityofSantaMonica/hackthebeach/settings) should be configured with all of this.

On a side note, might I recommend [Netlify](https://www.netlify.com/)? They can handle deploys like this easily without having to get GitHub + Travis + Surge.sh all communicating 👍

**Pull request merged**
